HandyBus/handybus-admin-web-latest

- src/app/actions/shuttle.action.ts
- src/app/shuttles/(home)/components/ShuttleTable.tsx
- src/app/shuttles/(home)/layout.tsx
- src/app/shuttles/(home)/page.tsx
- src/app/shuttles/new/form.type.ts
- src/app/shuttles/new/layout.tsx
- src/app/shuttles/new/page.tsx
- src/app/upload-image/components/URLView.tsx
- src/app/upload-image/layout.tsx
- src/app/upload-image/page.tsx
- src/components/guide/Guide.tsx
- src/services/client.ts
- src/services/config.ts
- src/types/dailyShuttle.type.ts
- src/types/shuttle.type.ts
어떤 변경 사항이 있나요?
* 셔틀 목록을 조회(GET)할 수 있습니다.
* 셔틀을 등록(POST)할 수 있습니다.
* 포스터 이미지 업로드를 돕기 위한 이미지 업로드 페이지를 추가했습니다.
https://github.com/user-attachments/assets/651c0cc0-689a-4645-b89e-df900390f839
> feat: 셔틀 목록 조회 및 추가

- src/app/actions/route.action.ts
- src/app/shuttles/[shuttle_id]/(home)/components/DailyShuttleTable.tsx
- src/app/shuttles/[shuttle_id]/(home)/components/Shuttle.tsx
- src/app/shuttles/[shuttle_id]/(home)/layout.tsx
- src/app/shuttles/[shuttle_id]/(home)/page.tsx
- src/app/shuttles/[shuttle_id]/dates/[daily_id]/(home)/layout.tsx
- src/app/shuttles/[shuttle_id]/dates/[daily_id]/(home)/page.tsx
- src/app/shuttles/[shuttle_id]/dates/[daily_id]/routes/new/layout.tsx
- src/app/shuttles/[shuttle_id]/dates/[daily_id]/routes/new/page.tsx
- src/app/shuttles/[shuttle_id]/raw/layout.tsx
- src/app/shuttles/[shuttle_id]/raw/page.tsx
- src/components/json/JSONViewer.tsx
- src/components/link/BlueButton.tsx
- src/types/route.type.ts
**기존 #6 과 중복되는 변경사항이 있어, 고유 변경사항은 [여기](https://github.com/HandyBus/handybus-admin-web-latest/pull/7/files/ec533112043d5a6064e938df5c4f3a1ade6adbfd..90411029c968f0f25c69014a45786298f0f363f2)서 확인하시면 됩니다.**
어떤 변경 사항이 있나요?
* 셔틀 상세 뷰를 추가했습니다.
* 일일 셔틀 상세 뷰를 추가했습니다.
* 노선 추가 폼을 추가했습니다.
https://github.com/user-attachments/assets/628a1140-8d38-4cdd-9f25-8af09b1123c3
> feat: 셔틀 상세 뷰 및 노선 추가

- package-lock.json
- package.json
- src/app/actions/artists.action.ts
- src/app/actions/hub.action.ts
- src/app/actions/logout.action.ts
- src/app/actions/regions.action.ts
- src/app/actions/route.action.ts
- src/app/actions/shuttle.action.ts
- src/app/artists/(home)/components/ArtistTable.tsx
- src/app/artists/(home)/page.tsx
- src/app/shuttles/(home)/components/ShuttleTable.tsx
- src/app/shuttles/(home)/page.tsx
- src/app/shuttles/[shuttle_id]/(home)/components/DailyShuttleTable.tsx
- src/app/shuttles/[shuttle_id]/dates/[daily_id]/(home)/page.tsx
- src/app/shuttles/[shuttle_id]/dates/[daily_id]/routes/new/page.tsx
- src/app/shuttles/new/form.type.ts
- src/components/map/KakaoMap.tsx
- src/components/map/KakaoMap.types.ts
- src/types/artist.type.ts
- src/types/bus.type.ts
- src/types/dailyShuttle.type.ts
- src/types/date.type.ts
- src/types/demand.type.ts
- src/types/hub.type.ts
- src/types/region.type.ts
- src/types/route.type.ts
- src/types/shuttle.type.ts
다른 PR을 위해 미리 연 PR입니다.
* headless ui 라이브러리를 추가했습니다.
* api에 대응되는 server action 및 관련 타입을 만들었습니다.
어떤 변경 사항이 있나요?
- 관련 스크린샷
> feat: api 대응 action 및 type 생성

- src/app/shuttles/[shuttle_id]/dates/[daily_id]/routes/[route_id]/(home)/page.tsx
- src/app/shuttles/[shuttle_id]/dates/[daily_id]/routes/[route_id]/(home)/types/table.type.tsx
- src/app/shuttles/[shuttle_id]/dates/[daily_id]/routes/[route_id]/buses/new/layout.tsx
- src/app/shuttles/[shuttle_id]/dates/[daily_id]/routes/[route_id]/buses/new/page.tsx
- src/app/shuttles/[shuttle_id]/dates/[daily_id]/routes/[route_id]/buses/new/types/form.type.ts
- src/app/shuttles/[shuttle_id]/dates/[daily_id]/routes/new/page.tsx
어떤 변경 사항이 있나요?
* 임시 노선 상세 페이지를 추가했습니다.
* 버스 추가 페이지를 추가했습니다.
https://github.com/user-attachments/assets/1c60bdbd-4858-4a77-b97a-de9317be117a
버스가 추가에 성공했다는 응답 후에도 조회가 안 되는건 백엔드 버그인 듯 합니다 (슬랙 참고)
> feat: 간단한 노선 상세 페이지 및 버스 추가 페이지

- src/types/payment.type.ts
> fix: 결제 타입 수정

- src/types/payment.type.ts
> hotfix: 결제 타입 수정

- src/app/coupons/(home)/page.tsx
- src/app/coupons/(home)/types/table.type.tsx
- src/components/table/DataTable.tsx
쿠폰에서 대기 상태와 이에 호환되는 필터를 구현했습니다.
> fix: 쿠폰 대기 상태 추가

- src/app/shuttles/[shuttle_id]/dates/[daily_id]/routes/new/page.tsx
> hotfix: 노선 경유지 추가 반대로 된 오류 수정

- src/services/api/artists.services.ts
- src/services/api/bus.services.ts
- src/services/api/common.services.ts
- src/services/api/coupon.services.ts
- src/services/api/hub.services.ts
- src/services/api/reservations.services.ts
- src/services/api/route.services.ts
- src/services/api/shuttle.services.ts
> fix: api version 추가

- src/app/shuttles/(home)/page.tsx
> hotfix: 셔틀이 존재하지 않을 때 셔틀 추가하기 버튼 눌리도록 수정

- src/types/v2/event.type.ts
- src/types/v2/shuttleRoute.type.ts
EventViewEntity, ShuttleRouteViewEntity 에 createdAt, updatedAt 칼럼이 추가되면서 타입을 추가 반영합니다.
> fix: event view, shuttleroute view 타입에 created at updated at 추가

- package-lock.json
- package.json
- src/app/api/login/route.ts
- src/app/demands/(home)/types/table.type.tsx
- src/app/demands/[eventId]/(home)/types/table.type.tsx
- src/app/demands/[eventId]/dates/[dailyEventId]/(home)/page.tsx
- src/app/demands/[eventId]/dates/[dailyEventId]/(home)/types/table.type.tsx
- src/app/events/(home)/types/table.type.tsx
- src/app/events/[eventId]/(home)/components/Shuttle.tsx
- src/app/events/[eventId]/(home)/page.tsx
- src/app/events/[eventId]/(home)/types/table.type.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/(home)/page.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/(home)/page.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/routes/new/form.type.ts
- src/app/events/[eventId]/dates/[dailyEventId]/routes/new/page.tsx
- src/app/events/new/page.tsx
- src/app/events/new/types/form.type.ts
- src/components/input/DateInput.tsx
- src/components/input/DateTimeInput.tsx
- src/components/input/HubInput.tsx
- src/components/input/Input.tsx
- src/components/input/PartialRegionInput.tsx
- src/services/v2/event.services.ts
- src/utils/date.util.ts
어떤 변경 사항이 있나요?
지난 1월 17일 QA에서 나온 어드민 개선 필요 사항 중 다음을 반영했습니다. (노션 '운영 풀로우' 참고)
- [행사-생성] 아티스트 없이 추가하는 상황에서 오류 ✅
- [수요조사-자세히] 목적지행 수요가 아니고 목적지로 가는 방향에서의 수요? (목적지 방향 희망 승탑지 수요 + 줄글 설명 + 필요한 컬럼만 보여주기) ✅
- [노선-생성] 노선 추가시 date만 받도록 하기 ✅
- [노선-생성-가격] input 스크롤 방지 ✅
- [노선-생성-시간] 기본적으로 dailyEvent 시간으로  ✅
- [행사-목록] 행사 이름이 제일 첫 컬럼이 되도록 ✅
그 외 수정사항:
DateInput, DateTimeInput을 추가했습니다.
페이지 제목을 일부 수정했습니다.
> fix: 어드민 운영 플로우 qa 반영

- src/app/reservations/(home)/page.tsx
- src/services/config.ts
- src/services/shuttleOperation.service.ts
어떤 변경 사항이 있나요?
cursor기반 pagination된 api가 더 이상 number가 아니게 된 api 변경 사항을 반영했습니다.
> fix: pagination api

- src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/page.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/routes/new/page.tsx
노선 추가 및 수정하기에서 alert 안뜨는 이슈 해결하였습니다.
어떤 변경 사항이 있나요?
- 관련 스크린샷
> fix(행사): 노선 추가 및 수정하기에서 alert 안뜨는 이슈 해결

- src/components/input/CoordInput.tsx
카카오맵에서 키워드로 검색 기능을 추가했습니다.
https://github.com/user-attachments/assets/760ce367-d41d-4a3e-ab5c-c76b03faf312
> feat: 카카오맵 검색 기능 구현

- .github/CODEOWNERS
- .github/auto_assign.yml
> chore: code owner 파일 삭제

- src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/page.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/routes/new/page.tsx
- src/components/input/NumberInput.tsx
Number Input의 보여지는 값에 쉼표가 처리되어 표시되도록 했습니다.
https://github.com/user-attachments/assets/b9d6ca02-aa4f-4303-8655-1cc002e33555
> feat: number input의 보여지는 값에 쉼표 처리

- .github/workflows/assign_reviewer.yml
> chore: 리뷰어 자동 배정 액션 추가

- public/icons/toasty-check.svg
- src/app/users/components/UserFilter.tsx
- src/app/users/hooks/useUserFilter.tsx
- src/app/users/page.tsx
- src/app/users/table.type.tsx
- src/components/input/Input.tsx
- src/components/layout/Nav.tsx
- src/components/loading/Loading.tsx
- src/components/toast-container/ToastContainer.tsx
- src/components/tool-tip/ToolTip.tsx
- src/constants/common.ts
- src/services/config.ts
- src/services/userManagement.service.ts
- src/types/user.type.ts
- src/utils/date.util.ts
- src/utils/stringifier.util.ts
유저 대시보드를 구현했습니다.
https://github.com/user-attachments/assets/5e299579-6c08-4dde-85a3-d884b55e64fd
> feat: 유저 대시보드

- src/app/login/page.tsx
- src/app/reservations/(home)/types/table.type.tsx
- src/app/users/[userId]/components/coupons-table/CouponsTable.tsx
- src/app/users/[userId]/components/coupons-table/table.type.tsx
- src/app/users/[userId]/components/demands-table/DemandsTable.tsx
- src/app/users/[userId]/components/demands-table/table.type.tsx
- src/app/users/[userId]/components/reservations-table/ReservationsTable.tsx
- src/app/users/[userId]/components/reservations-table/table.type.tsx
- src/app/users/[userId]/components/reviews-table/ReviewsTable.tsx
- src/app/users/[userId]/components/reviews-table/table.type.tsx
- src/app/users/[userId]/components/user-table/UserTable.tsx
- src/app/users/[userId]/components/user-table/table.type.tsx
- src/app/users/[userId]/page.tsx
- src/app/users/hooks/useUserFilter.tsx
- src/app/users/page.tsx
- src/services/userManagement.service.ts
- src/types/coupon.type.ts
- src/types/reservation.type.ts
- src/utils/stringifier.util.ts
유저 상세 페이지를 구현했습니다.
https://github.com/user-attachments/assets/ab095875-bea0-4d40-8800-4a98c080ec08
> feat: 유저 상세 페이지

- src/app/hubs/(home)/types/table.type.tsx
- src/components/viewer/RegionHubViewerModal.tsx
- src/services/location.service.ts
- src/types/hub.type.ts
region hub 조회 v2 api 에 맞춰서 타입 마이그레이션을 진행했습니다.
> fix: regionhub v2 types migrations

- src/app/hubs/(home)/components/RegionHubFilter.tsx
- src/app/hubs/(home)/hooks/useRegionHubFilter.tsx
- src/app/hubs/(home)/page.tsx
- src/app/hubs/(home)/types/table.type.tsx
- src/components/input/HubInput.tsx
- src/services/location.service.ts
거점지 전체 조회 및 필터를 구현했습니다.
https://github.com/user-attachments/assets/c91a8f67-5b8a-492e-b92f-57dbe4b7b948
> feat: 거점지 전체 조회 및 필터 구현

- src/app/hubs/(home)/types/table.type.tsx
- src/app/hubs/[regionId]/[hubId]/edit/page.tsx
- src/app/hubs/[regionId]/[hubId]/edit/types/form.type.ts
- src/components/input/CoordInput.tsx
- src/data/regions.json
- src/services/location.service.ts
- src/types/hub.type.ts
- 장소 수정 기능이 추가되었습니다
- 설정되어있는 위치로 지도 초기화면이 보여집니다.
- [src/data/regions.json](https://github.com/HandyBus/handybus-admin-web-latest/pull/96/files#diff-3f156db933d3efb85894609054b95e3e0192fcd7b34630fddf18bd208f5fa1d2) 에서 number 타입으로 잘 못 표기되어있는 부분을 변경했습니다.
https://github.com/user-attachments/assets/5a8a6ffa-e6a9-412f-aa14-7b5293edbc18
> feat: 거점지 수정

- src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/buses/[busId]/edit/page.tsx
bus 수정하기 페이지의 코드를 리팩토링하였습니다.
bus 데이터가 있을때만 defaultValue를 주입하도록 의도하였습니다.
즉, defaultValue에 ''와 0과 같은 리터럴을 직접 주입하지 않습니다.
노선 수정하기 부문도 개선할 예정입니다. 
> refactor: bus 수정하기 페이지 코드 개선

- src/app/coupons/page.tsx
- src/app/coupons/table.type.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/conform.util.ts
- src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/page.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/routes/new/conform.util.ts
- src/app/events/[eventId]/dates/[dailyEventId]/routes/new/page.tsx
- src/app/events/new/page.tsx
- src/app/reservations/table.type.tsx
- src/app/users/[userId]/components/demands-table/table.type.tsx
- src/app/users/[userId]/components/reservations-table/table.type.tsx
- src/app/users/components/UserFilter.tsx
- src/app/users/page.tsx
- src/components/input/DateInput.tsx
- src/components/layout/TopLevelLayout.tsx
- src/utils/date.util.ts
> fix: 시간대 통일

- src/app/events/new/page.tsx
> chore: 테스트 코드 삭제

- src/app/events/[eventId]/edit/page.tsx
> fix: 행사 수정에서 날짜 수정시 안되던 이슈

- src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/components/Buses.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/table.type.tsx
- src/app/events/[eventId]/edit/page.tsx
버스 테이블에서 무한 렌더링이 발생하던 부분을 해결했습니다.
> fix: 버스 테이블 무한 렌더링 문제 해결

- src/app/events/table.type.tsx
- src/types/event.type.ts
> fix: 행사 대시보드 타입 변경 반영

- src/app/events/[eventId]/dates/[dailyEventId]/demands/page.tsx
- src/components/tool-tip/ToolTip.tsx
- src/constants/common.ts
수요조사 대시보드에서 추천 노선들의 기본 값들을 기획과 맞게 수정했습니다. 
해당 값들을 명시적으로 알 수 있도록 툴팁을 추가했습니다.
> chore: 추천 노선 변수 기본 값 변경 및 툴팁 구현

- src/app/events/[eventId]/edit/page.tsx
- src/app/events/new/page.tsx
- src/components/input/ArtistInput.tsx
- src/components/modal/CustomModal.tsx
- src/components/modal/NewArtistsModal.stories.ts
- src/components/modal/NewArtistsModal.tsx
셔틀 이름 -> 행사 이름으로 placeholder 변경
(UX 개선) 행사 추가/편집 페이지에서 아티스트를 모달로 추가할 수 있습니다.
성공시 토스트메시지로 아티스트 관리 페이지로 갈 수 있습니다.
input에 숫자, 영어 말고 한글 입력시 onSubmit 함수가 두번 호출되는 이슈가 있었습니다.
이건 한글이 자음모음따로인 상태일 수도 있고, 자음모음조합된 상태일 수도 있는데, 이를 각각 따로따로 인지하여 이벤트를 호출하기 때문입니다.
e.nativeEvent.isComposing 을 사용하여 체크하고 한번만 이벤트를 호출하여 해결하였습니다
[참고 문헌](https://velog.io/@starplanter/onKeyDown-%EC%9D%B4%EB%B2%A4%ED%8A%B8%EC%97%90%EC%84%9C-%ED%95%9C%EA%B8%80-%EC%9E%85%EB%A0%A5-%ED%9B%84-Enter%ED%82%A4-%EC%9E%85%EB%A0%A5-%EC%8B%9C-%EC%9D%B4%EB%B2%A4%ED%8A%B8%EA%B0%80-%EB%91%90-%EB%B2%88-%ED%98%B8%EC%B6%9C%EB%90%98%EB%8A%94-%EB%AC%B8%EC%A0%9C)
https://github.com/user-attachments/assets/27ccf8a6-9693-406a-a51d-d43c561e16d7
> feat(행사): placeholder 변경 및 행사 추가/편집 페이지에서 아티스트 추가 모달 반영

- src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/components/Buses.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/table.type.tsx
> feat: 버스 목록 테이블에 핸디 정보 추가

- src/types/event.type.ts
> chore: 행사 타입 수정

- src/app/locations/page.tsx
> fix: 장소 페이지에 무한스크롤 적용

- src/services/location.service.ts
장소 api 에서 페이지네이션 커서가 올밥르게 들어가지 않던 문제를 해결했습니다.
> fix: 장소 api 페이지네이션 커서 반영

- src/services/common.service.ts
auth를 사용하는 GET
/v1/core/admin/image/presigned-url
이미지 업로드를 위한 프리사인드 URL 생성 API 를 사용합니다
> refactor: core presigned url api 로 변경

- src/app/events/[eventId]/dates/[dailyEventId]/demands/components/Table.tsx
수요조사 목록의 기타 항목을 시군구 단위로 묶어서 정렬되도록 수정했습니다.
> fix: 수요조사 목록 기타 시군구로 정렬

- src/app/(home)/page.tsx
- src/app/users/[userId]/components/coupons-table/CouponsTable.tsx
- src/app/users/[userId]/components/demands-table/DemandsTable.tsx
- src/app/users/[userId]/components/reservations-table/ReservationsTable.tsx
- src/app/users/[userId]/components/reviews-table/ReviewsTable.tsx
- src/app/users/[userId]/components/user-table/UserTable.tsx
- src/app/users/[userId]/components/user-table/table.type.tsx
- src/app/users/components/UserFilter.tsx
- src/app/users/hooks/useUserFilter.tsx
- src/app/users/table.type.tsx
- src/services/userManagement.service.ts
- src/types/user.type.ts
- src/utils/stringifier.util.ts
> fix: 유저 타입 변경 반영

- src/services/config.ts
- src/services/core.service.ts
api에서 No Content가 올 때 대응을 수정했습니다.
> fix: no content 대응 수정

- src/app/users/[userId]/components/user-table/table.type.tsx
- src/app/users/components/UserFilter.tsx
- src/app/users/hooks/useUserFilter.tsx
- src/services/userManagement.service.ts
- src/types/user.type.ts
- src/utils/stringifier.util.ts
소셜 로그인 연동 여부 필터를 api 변동 사항에 맞추어 재구현했습니다.
> feat: 소셜 로그인 연동 여부 필터

- src/app/(home)/components/CancelledReservationPassengerCountChart.tsx
- src/app/(home)/components/DemandCountChart.tsx
- src/app/(home)/components/ReservationPassengerCountChart.tsx
- src/app/(home)/components/ReviewCountChart.tsx
- src/app/(home)/components/SalesCountChart.tsx
- src/app/(home)/components/UserCountChart.tsx
- src/app/(home)/page.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/demands/components/Table.tsx
- src/app/statistics/demands/components/RegionPieChart.tsx
- src/app/statistics/users/components/AgeRangeChart.tsx
- src/app/statistics/users/components/GenderChart.tsx
- src/app/statistics/users/components/MarketingConsentChart.tsx
- src/app/statistics/users/components/SocialLoginChart.tsx
- src/app/statistics/users/page.tsx
- src/app/users/hooks/useUserFilter.tsx
- src/app/users/page.tsx
- src/components/chart/ChartSection.tsx
- src/components/chart/CustomLineChart.tsx
- src/components/chart/CustomPieChart.tsx
- src/components/input/CoordInput.tsx
- src/services/shuttleOperation.service.ts
- src/services/userManagement.service.ts
- src/types/coupon.type.ts
- src/types/dashboard.type.ts
- src/types/demand.type.ts
- src/types/reservation.type.ts
- src/types/reviews.type.ts
- src/types/user.type.ts
> feat: 유저 통계 페이지

- src/app/users/[userId]/components/user-table/table.type.tsx
- src/app/users/table.type.tsx
- src/types/user.type.ts
유저 progress가 tracking으로 변경된 사항을 대응했습니다.
> fix: 유저 progress 변경 대응

- src/app/banners/edit/BannerEditForm.tsx
- src/app/banners/page.tsx
> style: 배너 대시보드 설명 추가

- src/app/users/[userId]/components/user-table/table.type.tsx
- src/app/users/table.type.tsx
- src/types/user.type.ts
> fix: 유저 생성일 및 수정일 표시

- src/utils/parse.util.ts
- NEXT_PUBLIC_VERCEL_ENV 를 사용하면 vercel 에 배포된 deployement를 인식하여 분기처리할 수 있습니다.
> fix: silent parser alert production 에서 뜨지 않게 수정

- src/app/users/components/UserFilter.tsx
utc시간으로 반영하도록 변경했습니다.
dev 환경에서 테스트가 필요합니다
> fix: user filter last login time 에 utc 적용

- src/components/layout/Nav.tsx
- src/types/user.type.ts
네비게이션바의 모바일 디자인을 햄버거 메뉴로 구현했습니다.
> design: 네비게이션바 모바일 디자인

- src/app/events/[eventId]/dates/[dailyEventId]/demands/components/Map.tsx
수요조사 클러스터 목록이 state로 관리되도록 변경하여 가끔식 목록이 보이지 않던 현상을 해결했습니다.
> fix: 수요조사 클러스터 목록이 가끔씩 로드가 안되는 현상 해결

- .github/workflows/pr-labeler.yml
어드민에서도 자동으로 pr labeler를 달아줍니다.
> feat: add pr labeler 추가

- src/app/(home)/components/DemandCountChart.tsx
- src/app/(home)/components/ReservationPassengerCountChart.tsx
- src/app/(home)/components/ReviewCountChart.tsx
- src/app/(home)/components/SalesCountChart.tsx
- src/app/(home)/components/UserCountChart.tsx
- src/app/(home)/components/UserFunnelChart.tsx
- src/app/(home)/page.tsx
- src/app/statistics/users/components/AgeRangeChart.tsx
- src/app/statistics/users/components/GenderChart.tsx
- src/app/statistics/users/components/MarketingConsentChart.tsx
- src/app/statistics/users/components/SocialLoginChart.tsx
- src/app/statistics/users/page.tsx
- src/components/chart/ChartBox.tsx
- src/components/chart/CustomBarChart.tsx
- src/components/chart/CustomLineChart.tsx
- src/components/chart/CustomPieChart.tsx
- src/components/chart/chart.const.ts
- src/components/chart/chart.util.ts
- src/services/reservation.service.ts
- src/types/dashboard.type.ts
유저 참여 현황 차트를 구현했습니다.
현재 dev에서는 디버그 api로 생성한 데이터로 인해 차트가 올바르게 보여지지 않습니다.
> feat: 유저 참여 현황 차트

- src/app/(home)/components/UserFunnelChart.tsx
유저 현황 차트 값이 올바르게 반영되도록 수정했습니다.
> fix: 유저 현황 차트 값이 올바르게 반영되도록 수정

- src/app/(home)/components/UserFunnelChart.tsx
유저 현황 차트에서 index가 올바르게 들어가도록 수정했습니다.
> fix: 유저 현황 값 index 수정

- src/services/demand.service.ts
- src/services/review.service.ts
수요조사 카운트 api에서 옵션이 미반영되던 부분을 수정했습니다.
> fix: 수요조사 카운트 api 옵션 미반영 수정

- src/app/events/[eventId]/dates/[dailyEventId]/demands/components/Map.tsx
클러스터의 지역을 조회할 때 값이 많을 경우 카카오 api 측의 단 시간 내 많은 호출 방지로 인해 일부 클러스터가 표시되지 않던 문제를 해결했습니다.
관련 에러 참고자료: https://devtalk.kakao.com/t/api-503-service-unavailable/141746
> fix: 카카오 api의 단 시간 내 많은 호출 방지로 인한 클러스토 미표시 수정

- src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/reservations/components/BusTable.tsx
노선에 버스가 2대 이상 있을때, 하나의 버스에 최대 인원을 채우고도 계속 인원이 배차되던 버그를 고쳤습니다.
- 내부에 javascript 지역 변수를 사용해서 남은 좌석수를 반영하고 마지막에 상태에 반영하는 방식으로 해결했습니다.
- 찬찬히 살펴보니 handleFillUnassignedReservation 함수 구현이 foreach 문을 돌면서 state에 포함된 남은 좌석수를 채우는 로직인데요. react 상태로 editingBusWithSeats를 가지고 있고, foreach 내부에서 상태를 업데이트하는 부분이 문제였습니다. 
- call stack 에 쌓여있는 handleFillUnassignedReservation 함수는 javascript runtime이 처리할 때 함수 내부에서 foreach문이 포함되어있는 handleFillUnassignedReservation 함수가 끝나고 난뒤에 마이크로 태스크 큐(리액트의 상태 업데이트는 마이크로 태스크 큐와 유사한 우선순위로 처리된다고 하네요)에서 react 상태 업데이트를 진행하기 때문에 그런거 같아요.
```
const handleFillUnassignedReservation = () => {
if (!buses || !reservations) {
return;
}
const unAssignedReservations = reservations.filter(
(reservation) => reservation.shuttleBusId === null,
);
const newEditingBusAndReservations = …
```
> fix: handleFillUnassignedReservation 에서 남은 좌석수가 제대로 계산되지 않던 이슈 해결

- src/services/config.ts
204 no content 케이스를 처리하지 못하던 상황을 어드민에서도 적용해 해결하였습니다.
> fix: 204 no content 처리

- src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/utils/extractHubs.ts
- src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/utils/extractSortedShuttleHubs.util.ts
- src/app/events/[eventId]/dates/[dailyEventId]/routes/new/utils/extractHubs.ts
- src/services/shuttleRoute.service.ts
- src/types/shuttleRoute.type.ts
어떤 변경 사항이 있나요?
- 관련 스크린샷
PUT v2 api가 제거되고, v3 POST 및 PUT이 나와 api에 대응했습니다.
role 추가한 버전의 api에 대응해서 귀가행의 경우 첫번째 시퀀스, 목적지행의 경우 마지막 시퀀스를 role로 부여합니다.
> feat: shuttleRoute 폼에 role 추가, v3 api 대응

- src/types/reservation.type.ts
> fix: resevationViewEntity hasReview 필드를 reviewId 로 변경

- src/types/shuttleBus.type.ts
- src/utils/stringifier.util.ts
> feat: 7,9인승 스타리아 추가

- src/types/shuttleBus.type.ts
- src/utils/stringifier.util.ts
dev -> main 릴리즈를 진행하지 않고,
main 브랜치에 바로 필요한 작업사항을 병합합니다.
> feat: 7,9인승 스타리아 추가 (direct to main)

- src/app/reservations/components/RequestRefundDialog.tsx
환불 기능에 confirm 을 추가하여, 환불 과정에 실수를 방지할 수 있게 한 번 더 방지턱을 줍니다
> feat: 환불 기능에 confirm 추가

- src/app/reservations/[reservationId]/types/payment.table.type.ts
백엔드 스키마 용어에 맞게 칼럼명을 변경합니다.
총금액 -> 원금
할인 전 금액 -> 결제 금액
> fix: 테이블 용어 변경

- src/constants/handyPartyArea.const.ts
- src/constants/handyPartyPriceTable.const.ts
핸디팟 용인, 시흥, 파주, 평택 권역을 추가했습니다.
> chore: 핸디팟 권역 추가

- src/app/events/new/page.tsx
- src/types/event.type.ts
> feat: 스포츠 행사 타입 반영

- src/app/events/[eventId]/dates/[dailyEventId]/routes/new/handy-party/components/Content.tsx
> fix: 핸디팟 노선 생성 기본값 수정

- src/app/events/[eventId]/edit/page.tsx
> feat: 행사 상태 변경

- src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/reservations/table.type.tsx
- src/app/reservations/components/CancelReservationDialog.tsx
- src/app/reservations/table.type.tsx
- src/components/dialog/EditHandyStatusDialog.tsx
- src/components/link/BlueButton.tsx
- src/types/event.type.ts
> feat: 예약 테이블 UI 통일

- src/app/coupons/new/page.tsx
- src/app/coupons/table.type.tsx
- src/app/events/[eventId]/page.tsx
- src/app/events/[eventId]/table.type.tsx
- src/services/coupon.service.ts
- src/types/coupon.type.ts
특정 행사에 대해서만 사용 가능한 쿠폰을 조회 및 생성할 수 있도록 기능을 추가했습니다.
> feat: 특정 행사에 대해서만 사용 가능한 쿠폰 조회 및 생성

- src/app/events/[eventId]/dates/[dailyEventId]/routes/new/handy-party/components/Content.tsx
- src/constants/handyPartyPriceTable.const.ts
> feat: KSPO DOME 단가표

- src/app/banners/components/BannerImageFileInput.tsx
- src/components/announcement/AnnouncementForm.tsx
- src/components/input/ImageFileInput.tsx
- src/services/core.service.ts
공지사항 생성 시 이미지를 업로드 할 수 있는 기능을 추가했습니다.
https://github.com/user-attachments/assets/974257f3-c606-490d-a30e-1a2f9178453a
> feat: 공지사항 생성 시 이미지 업로드 기능

- src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/components/EditForm.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/utils/transformToShuttleRouteRequest.ts
- src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/utils/validateShuttleRouteData.ts
- src/types/shuttleRoute.type.ts
노선 수정 시 수정된 값만 요청 바디에 포함되도록 수정했습니다.
> fix: 노선 수정 시 수정된 값만 포함

- src/app/coupons/new/page.tsx
- src/app/coupons/table.type.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/routes/new/handy-party/components/Content.tsx
- src/app/events/new/page.tsx
- src/components/input/EventInput.tsx
- src/services/event.service.ts
- src/types/coupon.type.ts
- src/utils/coupon.util.ts
수요조사 리워드 쿠폰 생성 로직을 구현했습니다.
특정한 코드 조합으로 이루어진 쿠폰을 생성하여 수요조사 시에 해당 쿠폰을 발급받도록 하는 방식으로 구현할 예정입니다.
> feat: 수요조사 리워드 쿠폰 생성

- src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/reservations/table.type.tsx
- src/app/reservations/[reservationId]/types/account.table.type.ts
- src/app/reservations/components/ReservationFilter.tsx
- src/app/reservations/hooks/userReservationFilter.ts
- src/app/reservations/table.type.tsx
- src/app/users/[userId]/components/reservations-table/table.type.tsx
- src/app/users/[userId]/components/user-table/table.type.tsx
- src/app/users/components/UserFilter.tsx
- src/app/users/hooks/useUserFilter.tsx
- src/app/users/table.type.tsx
- src/services/reservation.service.ts
- src/services/user.service.ts
- src/types/reservation.type.ts
- src/types/user.type.ts
어드민에서도 실명제 도입되었습니다.
- 유저, 행사, 예약에서 이름이 반영되었습니다.
- 닉네임과 전화번호 -> 이름, 닉네임, 전화번호로 3중 병기하여 표기합니다.
- 이름이 없는 유저는 '-' 로 표기됩니다.
- 탈퇴한유저는 탈퇴한 유저라고 표기합니다.
> feat: 실명제 도입

- src/app/events/[eventId]/dates/[dailyEventId]/EditDailyEventOpenChatUrl.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/page.tsx
- src/app/events/table.type.tsx
- src/components/link/BlueLink.tsx
- src/types/event.type.ts
어드민에서 오픈채팅방 링크를 추가/수정할 수 있습니다.
|공지방 링크가 없을때|모달창|
|-|-|
|<img width="737" height="660" alt="Screenshot 2025-08-06 at 6 00 39 PM" src="https://github.com/user-attachments/assets/29e0f8a1-de40-4fd3-b130-2f4e481c18e8" />|<img width="748" height="572" alt="Screenshot 2025-08-06 at 6 00 35 PM" src="https://github.com/user-attachments/assets/3b190f07-f76f-446e-8b75-848311844adc" />|
|공지방 링크가 있을때 노선 추가버튼|모달창|
|-|-|
|<img width="732" height="534" alt="Screenshot 2025-08-06 at 6 06 01 PM" src="https://github.com/user-attachments/assets/d8f60785-3de5-4492-822d-a85862266b5b" />|<img width="739" height="651" alt="Screenshot 2025-08-06 at 6 06 04 PM" src="https://github.com/user-attachments/assets/19ef846c-4c4e-43d6-a3c3-2891f82d108b" />|
|행사 대시보드에서 바로 노선추가를 할 수 없습니다. 오픈챗 공지방 url 을 입력하지 않고 노선 추가를 유도하지 …
> feat: 공지방 링크 추가/수정하기

- src/app/cancel-reasons/page.tsx
- src/app/cancel-reasons/table.type.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/page.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/table.type.tsx
- src/components/layout/Breadcrumbs.tsx
- src/components/layout/Nav.tsx
기존에 피드백 페이지에서 같이 보여지던 예약 취소 사유를 별도의 페이지로 분리하였습니다.
> feat: 예약 취소 사유 페이지

- src/app/coupons/table.type.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/handy-party/optimizer/components/CalculatedDataAndMapView.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/table.type.tsx
- src/app/events/page.tsx
> design: 텍스트 색상 수정

- src/app/announcements/[announcementId]/page.tsx
- src/app/announcements/components/AnnouncementFilter.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/demands/components/Map.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/demands/map.util.ts
- src/app/events/[eventId]/dates/[dailyEventId]/demands/page.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/page.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/components/PriceSectionEarlyBirdType.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/components/ShuttleRouteHubItems.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/reservations/components/BusTable.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/reservations/components/ReservationTable.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/reservations/table.type.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/routes/new/page.tsx
- src/app/events/components/EventFilter.tsx
- src/app/locations/components/RegionHubFilter.tsx
- src/app/reservations/table.type.tsx
- src/app/users/[userId]/components/reservations-table/table.type.tsx
- src/app/users/components/UserFilter.tsx
- src/components/chart/ChartBox.tsx
- src/components/chart/CustomBarChart.tsx
- src/components/table/BaseTable.tsx
- src/components/table/VerticalTable.tsx
기존에 사용하던 디자인 시스템의 색상 클래스들이 수정되어 있지 않던 부분들을 일괄적으로 수정했습니다.
> fix: 기존 디자인 시스템 색상 클래스 수정

- src/app/events/[eventId]/dates/[dailyEventId]/routes/new/components/single-route-form/HubsSection.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/routes/new/utils/validateShuttleRouteData.ts
- src/app/events/[eventId]/dates/[dailyEventId]/routes/utils/calculateRoute.ts
노선 소요시간을 계산할 때 결과값이 폼에 올바르지 않게 반영되는 버그를 수정했습니다.
> fix: 노선 소요시간 계산값 폼 미반영 버그 수정

- src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/utils/validateShuttleRouteData.ts
- src/app/events/[eventId]/dates/[dailyEventId]/routes/new/components/MultiRouteForm.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/routes/new/components/single-route-form/HubsSection.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/routes/utils/calculateRoute.ts
- src/app/events/[eventId]/dates/[dailyEventId]/routes/utils/roundNearestFiveMinutes.util.ts
노선 생성 시 소요시간 form 값과 input 값이 올바르게 동기화 되지 않던 문제를 해결했습니다.
또한 노선 소요시간 계산 로직에서 초 단위가 없어지도록 수정했습니다.
> fix: 소요시간 form 값과 input 값 동기화

- src/app/events/[eventId]/sales/components/SalesRow.tsx
- src/app/events/[eventId]/sales/components/SalesTable.tsx
매출 대시보드에서 챠량 대금에 차량수를 곱하여 계산되도록 수정했습니다.
> fix: 차량 대금에 차량 수 곱셈 계산

- src/app/events/[eventId]/dates/[dailyEventId]/page.tsx
> feat: 공지방 필수 생성 비활성화

- src/app/events/[eventId]/edit/page.tsx
- src/app/events/[eventId]/table.type.tsx
- src/app/events/new/page.tsx
- src/app/events/page.tsx
- src/components/input/ImageFileInput.tsx
- src/types/event.type.ts
행사 상세 이미지 칼럼을 반영하여 생성 및 수정할 때 삽입할 수 있도록 수정했습니다.
> feat: 행사 상세 이미지 칼럼 반영

- src/app/events/[eventId]/dates/[dailyEventId]/routes/new/handy-party/components/Content.tsx
> fix: 핸디팟 노선 개설 도착지 setter 함수 수정

- src/app/events/[eventId]/dates/[dailyEventId]/page.tsx
> fix: 일자별 탑승 정보 알림톡 전송 순차적 처리

- src/app/events/[eventId]/dates/[dailyEventId]/hooks/useExportPassengerList.tsx
- src/app/events/[eventId]/dates/[dailyEventId]/page.tsx
> fix: 탑승자 명단 추출 내 예외 처리 수정
