src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/(home)/page.tsx, src/app/events/[eventId]/dates/[dailyEventId]/routes/new/conform.util.ts, src/app/events/[eventId]/dates/[dailyEventId]/routes/new/form.type.ts, src/app/events/[eventId]/dates/[dailyEventId]/routes/new/page.tsx
- [버그수정] 행사 - dailyshuttle - 노선 : 목적지행과 귀가행의 거점지 정보가 반대로 표시되던 버그를 수정했습니다.
- [오타수정] 함수명 오타 수정 : fomated -> formatted, discound -> discount
- [기능추가] 행사 - dailyshuttle - 노선 추가 : 목적지, 출발지 순서 고정 및 삭제 비활성화처리
- [기능추가] arrival time validate alert 추가 : 앞으로 거점지들의 시간순서가 올바르지 않으면 등록시 경고알림창이 뜨고 등록이 실패합니다.
- 거점지들은 앞 -> 뒤 순서로 시간순서가 일치해야합니다.
- 또한 목적지행보다 귀가행 시간이 이른경우 등록이 실패합니다.
=> feat(행사): 거점지 시간 순서 정합성 체크 추가 및 버그 수정

src/components/input/HubInput.tsx
거점지의 위치를 선택해야하는 지점에서 거점지가 존재하지 않을때 '새로운 거점 만들기'라는 항목이 표시되고, 클릭하면 새 탭으로 거점지 추가하기 페이지가 열립니다.
=> feat(행사): 거점지가 비어있을때 새 거점 만들기로 새탭이동 추가

src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/page.tsx, src/app/events/[eventId]/dates/[dailyEventId]/routes/new/conform.util.ts, src/app/events/[eventId]/dates/[dailyEventId]/routes/new/form.type.ts, src/app/events/[eventId]/dates/[dailyEventId]/routes/new/page.tsx, src/components/input/HubInput.tsx, src/components/input/RegionInput.tsx, src/types/shuttleRoute.type.ts
노선 생성 페이지에서 경유지를 입력할 때 목적지행의 경유지들을 귀가행에 미러링 할 수 있는 기능을 추가했습니다.
https://github.com/user-attachments/assets/e72b19b1-0753-4f03-af9f-ce300bfba586
=> feat: 노선 생성 시 경유지 미러링 기능 추가

src/app/events/[eventId]/(home)/page.tsx, src/app/events/[eventId]/edit/page.tsx, src/app/events/[eventId]/edit/types/form.type.ts, src/app/events/new/page.tsx, src/services/shuttleOperation.service.ts, src/types/event.type.ts
행사 수정 페이지가 추가되었습니다.
- 일일행사의 수정전 데이터를 병렬 표기하였습니다.
- 새로운 일일행사 칼럼을 추가할 수 있습니다. 이런 경우엔 X 버튼이 표시되고 수정 및 삭제할 수 있습니다.
https://github.com/user-attachments/assets/d7d1b192-11ce-473a-8b8e-9795efe0bb73
=> feat: 행사 수정 페이지

src/components/input/ArtistInput.tsx, src/components/input/HubInput.tsx, src/components/layout/Nav.tsx
- 네비게이션바 - 아티스트가 사라집니다. 행사 - 행사추가/수정하기 페이지에서 접근할 수 있습니다.
- 거점지 : 이전엔 해당 시/도-시/군/구 선택후 거점지가 없을경우 새 거점지 추가하기 버튼이 표시됐는데, 언제나 표기됩니다.
- 아티스트 : 새 아티스트 추가하기 버튼이 표시됩니다.
=> feat: Hub/Artist input 에 새 거점지/아티스트 추가하기 버튼 삽입

src/app/events/[eventId]/dates/[dailyEventId]/demands/page.tsx, src/components/input/CoordInput.tsx, src/hooks/useKakaoMap.tsx
카카오맵 커스텀훅에서 스크립트 중복 로드가 안되도록 수정했습니다.
=> fix: 카카오맵 스크립트 중복 로드 방지

src/app/reservations/components/ReservationFilter.tsx, src/app/reservations/page.tsx, src/app/users/page.tsx, src/hooks/useInfiniteScroll.tsx
무한스크롤 커스텀 훅에서 다음 페이지 요청이 중복으로 들어가는 현상을 해결했습니다.
또한 debounced input을 필터가 있는 곳에 모두 적용시켰습니다.
=> fix: 무한스크롤 중복 요청 방지 및 debounced input 적용

src/app/reservations/table.type.tsx
기존에 핸디선발/거절을 누르면 예약상세로 리디렉트 되던 이슈를 해결하였습니다.
https://github.com/user-attachments/assets/0343a210-1bfc-4636-a0a6-84136c994e0f
=> fix: 예약관리에서 핸디 선발 안되던 이슈

src/app/events/[eventId]/dates/[dailyEventId]/demands/[eventId_tmp]/dates/[dailyEventId_tmp]/table.type.tsx, src/app/events/[eventId]/dates/[dailyEventId]/demands/table.type.tsx, src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/page.tsx, src/app/events/[eventId]/dates/[dailyEventId]/routes/new/page.tsx, src/app/locations/[regionId]/hubs/[hubId]/edit/page.tsx, src/app/locations/components/RegionHubFilter.tsx, src/app/locations/new/page.tsx, src/app/locations/page.tsx, src/components/input/HubInput.tsx, src/components/layout/Breadcrumbs.tsx
breadcrumb를 고도화 하여 현재 경로에 올바른 페이지 목록들이 이름과 함께 보여지도록 했습니다.
=> feat: breadcrumb 고도화

src/app/events/[eventId]/dates/[dailyEventId]/demands/components/Table.tsx, src/app/events/[eventId]/dates/[dailyEventId]/demands/table.type.tsx
기타 수요조사 결과가 하단에 모여서 배치되도록 수정했습니다.
=> fix: 기타 수요조사 결과가 아래에 배치되도록 수정

src/app/events/table.type.tsx
행사 수요조사 링크 텍스트에 수요조사 수가 표시되도록 했습니다.
=> design: 행사 수요조사 링크 텍스트에 수 표시

src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/page.tsx, src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/page.tsx, src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/reservations/components/BusTable.tsx, src/app/events/[eventId]/dates/[dailyEventId]/routes/new/page.tsx, src/types/shuttleRoute.type.ts, src/utils/stringifier.util.ts
어드민에서 목적지행, 귀가행 -> 가는편, 오는편으로 네이밍을 변경햇습니다.
노선 추가하기에서 가격 지정 순서를 가는편, 오는편, 왕복 -> 왕복 가는편 오는편 순서로 반영되었습니다.
=> style: 네이밍 변경 가는편 오는편 및 순서 변경

src/app/events/[eventId]/dates/[dailyEventId]/routes/new/page.tsx, src/app/events/new/page.tsx, src/components/form/Form.tsx
이벤트 추가, 노선 추가 페이지에서 폼 submit 시에 submit button 을 비활성화 처리하였습니다.
SubmitButton 에서 PropsWithChildren 타입을 갖고 있던데 file change 처럼 저렇게 수정해서 사용하는것이 맞는걸까요? 낯설어서 여쭤봐요
=> feat: submit 시에 버튼 비활성화처리

src/app/events/[eventId]/dates/[dailyEventId]/routeDemand.util.ts, src/app/events/[eventId]/dates/[dailyEventId]/table.type.tsx, src/app/reservations/[reservationId]/types/route.table.type.ts, src/components/input/ShuttleRouteInput.tsx, src/services/shuttleRoute.service.ts, src/types/region.type.ts, src/types/reservation.type.ts, src/types/shuttleRoute.type.ts
추가 노선 개설 요청 조회를 추가했습니다.
- 추가 노선을 개설한 시점의 요청 수를 기록할 수 있도록 저장 기능을 추가로 구현해두었습니다.
- 노선 좌석 예매 현황 열을 추가했습니다.
=> feat: 추가 노선 개설 요청 조회

src/app/(home)/components/ReservationPassengerCountChart.tsx, src/components/chart/ChartBox.tsx
예약 탑승객 수에 취소한 예약 탑승객 수가 합산되도록 수정했습니다.
=> fix: 예약 탑승객 수에 취소한 예약 탑승객 수 합산

src/app/locations/map/components/hubsMap.tsx, src/app/locations/map/createOverlayHTML.util.ts, src/app/locations/map/page.tsx, src/app/locations/new/page.tsx, src/components/input/CoordInput.tsx
문제 원인을 분석해보았습니다. 아래의 두가지 시나리오가 모두 생길 수 있어서 간헐적으로 일어나는 일이라고 판단했어요.
1. 카카오맵 Script 가 로드가 완료되면 콜백함수인 () => initailizeMap() 을 실행함. -> 지도 초기화 완료.
2. get regionHubs 요청이 완료됨. -> 의존성을 걸어둔 useEffect에서 displayHubs() 호출 -> 정류장에 핀 성공적으로 그림.
*getRegionHubs API 요청이 비동기적으로 이루어짐.
1. (그래서 카카오맵 script 가 로드되기 전) get 요청이 완료되면 의존성을 걸어둔 useEffect에서 displayHubs를 호출 
-> 지도가 초기화 되지 않아 if (!kakaoMaps.current) return 문에 의해 함수 종료.
2. 카카오맵 Script 가 로드가 완료되면 콜백함수인 () => initailizeMap() 을 실행함. -> 지도 초기화 완료.
그러나 displayHubs를 다시 호출하지 않음. -> 정류장핀이 그려지지 않음.
initailizeMap() 함수안에 mapInitialized 상태를 true로 둬서, 카카오맵 초기화 후 다시 displayHubs를 호출하도록 함.
- (장소 공통) 줌레벨 5 이상에서 클릭시 줌 레벨 4로 변경 -> 줌 레벨 5이상에서 한번 클릭시 줌 레벨 -1
- (지도 보기) 지도 클릭시 생기는 파란색 핀을 클릭할 경우 해당 좌표를 반영해서 새 정류장 추가하기 새 창으로 열립니다.
hubsMap.tsx 를 중복 코드 감소 및 가독성 개선을 목표로 리팩토링하였습니다. …
=> feat: 정류장 핀 로드 이슈 해결 및 기능 개선

src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/page.tsx, src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/table.type.tsx, src/types/shuttleBus.type.ts, src/utils/date.util.ts
노선 매출에 대한 정보가 노선 상세 페이지에서 표시되도록 수정했습니다.
또한 가독성 향상을 위해 기존에 Callout 안에 있던 정보들을 테이블 안으로 옮겼습니다.
=> feat: 노선 매출 정보 표시

src/app/locations/[regionId]/hubs/[hubId]/edit/page.tsx, src/app/locations/components/MapGuides.tsx, src/app/locations/components/MapGuidesAtNewEditPage.tsx, src/app/locations/map/components/hubsMap.tsx, src/app/locations/map/page.tsx, src/app/locations/new/page.tsx, src/components/input/CoordInput.tsx, src/utils/region.util.ts
어드민 장소에서 사용하던 지도의 인터렉션 기능 추가 및 개선
- 줌 레벨이 6 이상 일때 지도를 왼쪽 클릭 하게되면 줌 인이 되는 방식에서 더블클릭시 줌 인으로 간단하게 변경
- 기존의 방식인 마우스 왼쪽 클릭 대신 마우스 오른쪽 클릭시 핀을 설정합니다.
- 도움말이 추가되었습니다.
- 지도 보기 페이지에서 첫 렌더링시에 에러가 발생하던 이슈
- 지도 추가/수정하기에서 drag end, zoom changed 시 마다 kakao api (geocoder.coord2Address) 가 2번씩 호출되던 이슈
- address 를 split 해서 쓰지 않고 kakao api 에서 제공되는 depth name을 사용하도록 변경
- region.uitl.ts 와 같은 오타 수정
- toAddress 는 new Promise 를 반환하므로 async 키워드가 필요없습니다. -> async 삭제
- then 을 사용하지 않고 async await 을 사용하도록 변경
https://github.com/user-attachments/assets/2a45b0a5-411b-4a0d-ac5e-96e70c1addce
=> feat: 장소 - 지도 인터렉션 기능 추가 및 개선

src/app/events/[eventId]/dates/[dailyEventId]/routes/new/page.tsx, src/app/events/[eventId]/dates/[dailyEventId]/routes/utils/calculateRoute.ts
calculateRoute.ts(자동 경로 소요시간 계산) 를 개선하였습니다.
- 가는 편에서필요한 폼을 채우지 않았을 경우 alert가 3번 -> 1번 표시되도록 변경하였습니다.
- 가는 편에서 자동 경로 소요시간을 계산했을때 절대값인 10분이상 차이가 날때도 처리되도록 변경하였습니니다.
- 응집성을 높이고, 결합도를 낮추는 방향으로 코드를 개선하였습니다.
- 기존의 코드는 계산과 상태 업데이트라는 두 가지 책임을 가지고 있어 단일 책임 원칙(SRP)에 위배되었습니다. 함수는 하나의 명확한 책임을 가지도록 변경하고자 합니다..
- 또, 계산함수에 react-hook-form의 setValue와 getValues에 높은 의존성을 지니고 있었습니다. 이를 개선하고자 합니다.
- jest + React Testing Library 를 활용한 단위/통합테스트를 고려하고 있었습니다. (Playwright, Cypress 와 같은 e2e 테스트는 QA팀이 없는 상황에서 도입해볼만 하지만, 다른 종류의 테스트에 비해 비용이 제일 많이 들고 변경사항이 발생하면 테스트코드가 쉽게 깨지는 단점이 있습니다.)
- 가장 비용이 낮은 unit 테스트에서는 아주 빠르고 간단하게 적용이 가능했습니다. 
- 다만, 코드 변경에도 테스트 코드가 깨지지 않는 통합테스트까지 반영되어야 효능이 있을 것이라고 생각했는데요. 노선 수정 페이지에서 사용하려 시도해보니 쉽게 적용할 수는 없었습니다. 알 수 없는 오류를 디버깅하는데만 생각보다 많은 시간이 소요됐고, 테스트 코드를 작성하는 비용도 적진 않았습니다. 
- 궁극적으로는 테스트 코드를 …
=> refactor: 코드 개선 및 alert 3번 뜨는 것 방지 (+ Testing 에 대한 고심)

src/app/events/[eventId]/dates/[dailyEventId]/routes/new/page.tsx, src/app/events/[eventId]/dates/[dailyEventId]/routes/utils/calculateRoute.ts
- alert 클릭 안되던 이슈, 가는편-출발지의 시각이 5분 내림 적용이 안되던 이슈를 해결하였습니다.
- 경로소요시간이 완료되었을때 완료되었다는 확인 alert를 표시합니다.
if 의 조건문에 confirm 을 사용하면 브라우저 대화창의 클릭이벤트가 씹힐 수 있습니다.
이를 confirm 을 변수 저장하는 방법으로 해결하였습니다. 왜 이것이 문제해결이 도움이 되는지 이해하지 못하였습니다 (혹시 아시나요?)
추측되는 원인은 아래와 같아요... (sonnet-3.7) 자세한 내용은 추후 issue 에서 다뤄볼게요.
React에서 상태 업데이트는 비동기적으로 일어나며, 일반적으로 이벤트 핸들러가 완료된 후에 일괄 처리됩니다.
타이밍 불일치 원인:
confirm() 호출은 JavaScript 실행을 일시 중단시키고, 사용자 응답을 기다립니다
이 중단 시점에서 React는 아직 상태 업데이트를 처리하지 않았을 수 있습니다
조건문이 실행될 때, 상태는 아직 이전 값을 유지하고 있을 가능성이 높습니다
결과적으로 confirm 응답과 상태 업데이트 사이에 '경쟁 상태(race condition)'가 발생할 수 있습니다
브라우저의 이벤트 시스템은 이벤트 버블링(하위 요소에서 상위 요소로)과 캡처링(상위 요소에서 하위 요소로) 단계로 작동합니다.
처리 오류 원인:
confirm() 다이얼로그가 표시되면 진행 중이던 이벤트 흐름이 중단됩니다
사용자가 응답한 후, 원래 진행 중이던 이벤트 처리가 계속됩니다
이 시점에서 React의 합성 이벤트 시스템과 브라우저의 네이티브 이벤트 처리가 동기화되지 않을 수 있습니다
특히 여러 …
=> fix: 경로소요시간 계산하기 

src/app/locations/[regionId]/hubs/[hubId]/edit/form.type.ts, src/app/locations/[regionId]/hubs/[hubId]/edit/page.tsx, src/app/locations/components/RegionHubFilter.tsx, src/app/locations/hooks/useRegionHubFilter.tsx, src/app/locations/location.type.ts, src/app/locations/new/page.tsx, src/app/locations/table.type.tsx, src/app/locations/utils/getTags.util.ts, src/components/button/Toggle.tsx, src/services/hub.service.ts, src/services/shuttleStops.service.ts, src/types/hub.type.ts, src/types/shuttleStop.type.ts
장소에 행사장, 정류장의 태그기능이 추가되었습니다.
(1) 장소 추가 페이지에서 장소 태그 선택 가능
(2) 장소 수정 페이지에서 장소 태그 선택 가능
(3) 장소 대시보드에서 칼럼 추가 및 필터 선택가능
장소 대시보드에서 필터 초기화 되지 않던 이슈 해결
행사 추가/수정, 노선 추가/수정 에서 행사장/정류장 태그만 regionHub 목록에 표시
-> 기존에 존재하는 정류장들에 태그 반영 작업이 되어있지 않은데 당장 행사장/노선 생성/수정 작업에 차질이 생길 것을 우려하여 운영팀에서해당 작업이 끝나면 해당 부분을 반영할 예정입니다.
- 장소 추가/수정을 완료하려면 addHub, putShuttleStop API를 차례로 쏴야합니다. 그런데 피치못할 사정으로 addHub만 성공하고 putShuttleStop 은 정상적으로 요청이 처리되지 않는 경우가 이론적으로 생길 수 있습니다. (브라우저가 꺼진다는 등) 이럴때는 따로 처리할 수 있는 방법이 없습니다. 만약에 생기더라도 장소는 추가/수정 완료되고 태그만 붙지 않는 거라. 위험하진 않긴 합니다...  예전에 우리 함께 이야기했던 백엔드에서 gateway 를 도입해서 원하는 형식에 맞게 엔드포인트를 재조립 하는 방법이 되어야 근본적으로 해결될 것 같긴해요
- interface TagStates 는 장소 추가하기와 수정하기, getTags() 함수에서 쓰이는데요. 처음엔 이를 type 파일로 분리시킬까 생각을 했었는데, 다른 곳에서 interface를 type 파일로 분리한 곳이 없고, 대게 컴포넌트 파일이나, service 파일에서 선언해두고 있더라고요. 
혹은 …
=> feat: 장소 태그 추가

public/icons/bus-stop-marker-cyan.svg, public/icons/bus-stop-marker.svg, public/icons/default-marker.svg, public/icons/event-venue-marker.svg, src/app/locations/map/components/hubsMap.tsx, src/components/input/CoordInput.tsx
장소 태그 반영 두번째 작업입니다.
- 장소 필터 삭제 (기획 변경으로 이후 pr 에서 태그에 따라 필터링하는 걸 반영하겠습니다.)
- 장소 - 지도 보기, 장소 추가/수정 페이지에서 정류장들이 부여된 태그에 따라 다르게 보여집니다. 
- 회색핀(미설정), 남색핀(버스정류장), 초록핀(행사장소)
- 많은 핀들이 지도에 보일 수록 성능이 느려져 이후 최적화 작업을 진행할 예정입니다. (일정 줌레벨 이상에서는 갯수만 보여주거나... 혹은 성능이 느려지는 원인을 찾아서 해결할 수 있거나..)
| 스크린샷 |
|--------|
| ![Screenshot 2025-04-01 at 4 04 06 PM](https://github.com/user-attachments/assets/301f2c61-2fc2-4039-bc56-5f477704f95a)  |
| ![Screenshot 2025-04-01 at 4 04 12 PM](https://github.com/user-attachments/assets/4dba92a9-7b95-4fee-af7a-e871638a7ac7)  | 
=> feat: 지도에 태그에 따라 핀 구분하기

src/components/input/CoordInput.tsx
간혹 경기도 고양시 덕양구 처럼 region_2depth_name에서 고양시 덕양구와 같은 형식으로 api response 가 오는 경우 지역 정류장 정보를 갖고오지 못하는 이슈가 발견 되어 이를 해결하였습니다.
=> fix: 특정 지역의 정류장 정보 가져와지지 않는 에러 해결

public/icons/bus-stop-marker-cyan.svg, public/icons/bus-stop-marker.svg, public/icons/default-marker.svg, public/icons/event-venue-marker.svg, src/app/locations/map/components/hubsMap.tsx, src/components/input/CoordInput.tsx
장소 태그 반영 두번째 작업입니다.
- 장소 필터 삭제 (기획 변경으로 이후 pr 에서 태그에 따라 필터링하는 걸 반영하겠습니다.)
- 장소 - 지도 보기, 장소 추가/수정 페이지에서 정류장들이 부여된 태그에 따라 다르게 보여집니다. 
- 회색핀(미설정), 남색핀(버스정류장), 초록핀(행사장소)
- 많은 핀들이 지도에 보일 수록 성능이 느려져 이후 최적화 작업을 진행할 예정입니다. (일정 줌레벨 이상에서는 갯수만 보여주거나... 혹은 성능이 느려지는 원인을 찾아서 해결할 수 있거나..)
| 스크린샷 |
|--------|
| ![Screenshot 2025-04-01 at 4 04 06 PM](https://github.com/user-attachments/assets/301f2c61-2fc2-4039-bc56-5f477704f95a)  |
| ![Screenshot 2025-04-01 at 4 04 12 PM](https://github.com/user-attachments/assets/4dba92a9-7b95-4fee-af7a-e871638a7ac7)  | 
=> feat: 지도에서 태그에 따른 다른 이미지의 핀을 보여줌 (base develop으로 다시 pr을 열었습니다.)

src/app/events/[eventId]/edit/page.tsx
이벤트 수정페이지에서 date 가 korean Time이 아니어서 수정완료가 안되던 이슈를 해결하였습니다.
- 해당 이벤트의 time 들이 ISOString으로 관리되고 있지 않고, format(yyyy-mm-dd)로 되어있던 부분을 변경했습니다.
이 때문에 새로 추가한 date는 utc 로 관리되고있는데, 기존의 행사 date들이 yyyy-mm-dd 형식으로 관리되고있어. API 요청이 실패하는 이슈를 해결했습니다.
=> fix: 이벤트 수정페이지에서 date 가 korean Time이 아니어서 수정완료가 안되던 이슈 해결

src/app/events/table.type.tsx
행사탭의 행사 날짜에 정렬을 적용하였습니다.
이전에는 아래의 이미지처럼 시간이 뒤죽박죽으로 보이는 이슈가 있습니다.
=> fix: 행사탭의 행사 날짜들 정렬 적용

src/app/events/page.tsx, src/app/events/table.type.tsx
이전 #199 작업 이후 버그를 발견했습니다.
행사 목록에서 dailyEvents 들은 올바른 순서대로 표기되는데 막상 상세 정보를 눌러서 나오는 페이지들은 다른 dailyEvents 에 속하는 페이지였습니다. 
-> `table.type.tsx` 에서 정렬을 수행하지 않고, `app/events/page.tsx` 에서 `dailyEvents`정렬을 진행합니다.
| 수정 전 | 수정 후 |
|--------|--------|
| <img width="742" alt="Screenshot 2025-05-13 at 1 30 14 PM" src="https://github.com/user-attachments/assets/1a20def8-27e2-4286-9628-13997f7e9eb8" /> | <img width="738" alt="Screenshot 2025-05-13 at 1 29 16 PM" src="https://github.com/user-attachments/assets/ae1aa073-0e55-45e0-90c0-1d6d9c173688" /> |
=> fix: 행사 dailyEvents 정렬 이슈 해결

src/app/events/[eventId]/edit/form.type.ts, src/app/events/new/form.type.ts, src/types/event.type.ts
일자별 행사의 수요조사 종료 시간을 반영했습니다.
현재 14일 전으로 자동으로 들어가도록 처리했고, 추후 폼 내부에서 개별적으로 설정 가능하도록 수정할 예정입니다.
=> feat: 일자별 행사의 수요조사 종료 시간 반영

src/app/coupons/new/page.tsx
쿠폰 생성시 UTC 날짜기준으로 post 하지 않던 이슈를 해결하였습니다.
상단 쿠폰이 버그픽스후 생성된 쿠폰입니다. 제대로된 날짜와 시간 값이 반영되어있습니다.
목록에서는 자세한 시간까지 표기되던데 이후 시간을 표현해줄 필요가 있는지 논의해보면 좋을 것 같네요 
필요하다면, 쿠폰 생성시 상세 시각까지 지정하도록 바뀌어야할 거 같아요
=> fix: 쿠폰 날짜 선택시 UTC로 반영 안되던 이슈 해결

package-lock.json, package.json, src/app/announcements/page.tsx, tailwind.config.ts
bold, link 외에 추가 요구된 기능을 반영하기위해 기본 마크다운 서식과 정렬을 반영합니다.
- ReactMarkdown 에디터에서 마크다운 서식을 보여주는데 필요한 tailwindcss/typography 를 설치 및 반영합니다.
- 공지사항 목록에 생성일 기준 내림차순 정렬됩니다
| 작성 중 화면 | 공지 글 조회 |
|--------|--------|
| <img width="668" alt="Screenshot 2025-06-05 at 5 58 06 PM" src="https://github.com/user-attachments/assets/eeba5ef4-022d-41d6-90c9-b012e37de200" /> | <img width="559" alt="Screenshot 2025-06-05 at 5 58 10 PM" src="https://github.com/user-attachments/assets/2511a801-cdca-4f62-bb6a-be489f4209d2" /> | 
=> design: 기본 마크다운 서식 반영

src/app/events/[eventId]/dates/[dailyEventId]/EditRouteStatusDialog.tsx, src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/form.type.ts, src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/edit/page.tsx, src/app/events/[eventId]/dates/[dailyEventId]/table.type.tsx, src/services/shuttleRoute.service.ts
행사 탭 - 노선 보기 - 노선 상태 변경 기능이 추가되었습니다.
- 노선의 상태를 변경할 수 있습니다.
- `OPEN` <-> `CLOSED`
- `OPEN` -> `CANCELLED`
- `CLOSED` -> `CANCELLED`
- `CANCELLED` or `ENDED` 에서는 상태변경 불가능
- invalidQuery 로 노선의 데이터를 갱신하는 방법으로는 상태를 바로 갱신할 수 없었습니다. 
- 이전에 듣기로 백엔드 구조상 업데이트되면 바로 데이터가 갱신되지 않는다고 알고 있는데요. 그래서 invalidateQueries로 노선의 데이터가 즉시 갱신되지 않는 듯 합니다.
- window.location.reload()로 브라우저 페이지를 강제 새로고침하도록 해두었습니다.
https://github.com/user-attachments/assets/b643dbc6-f8df-4cc7-a478-50c548a64f47
https://github.com/user-attachments/assets/43c81db6-996f-44a7-a3b2-81c82efce5d7
=> feat: 노선 상태 변경 기능 추가

src/app/events/[eventId]/dates/[dailyEventId]/demands/page.tsx, src/services/event.service.ts
수요조사 페이지를 들어올때마다 어떤 행사의 수요조사인지 기재가 되었으면 좋겠다는 건의사항에 따라 편의기능을 개발하였습니다.
- 행사명과 해당하는 일일행사 날짜를 함께 보여줍니다.
- react 의 suspense를 적용하였습니다. 선언적으로 코드를 작성할 수 있습니다. suspense와 함께 동작하기위해서 useQuery 대신 useSuspenseQuery를 사용하였습니다.
=> design: 수요조사 대시보드에 관련 행사 정보 표기 (Suspense 적용)

src/app/events/[eventId]/dates/[dailyEventId]/routes/[shuttleRouteId]/reservations/components/ReservationTable.tsx
행사 - 노선보기 - 예약상세에서 유효한 예약에 총인원수를 함께 표기합니다
| 유효한 예약 12건 (18인) / 합계 12건 [배차되지 않은 예약 인원 경우] | 유효한 예약 0건 (0인) / 합계 5건 [모두 배차된 예약 인원 경우] |
|--------|--------|
| <img width="880" alt="Screenshot 2025-06-27 at 2 39 49 PM" src="https://github.com/user-attachments/assets/3cde3604-d428-4d62-b190-408726c5db13" /> | <img width="877" alt="Screenshot 2025-06-27 at 2 39 42 PM" src="https://github.com/user-attachments/assets/8aa9090f-ce42-4058-bcfe-96fb4be79f98" /> | 
=> feat: 유요한 예약수에 인원수를 함께 표기

src/app/events/[eventId]/dates/[dailyEventId]/page.tsx, src/app/events/[eventId]/dates/[dailyEventId]/table.type.tsx, src/app/events/[eventId]/table.type.tsx, src/services/shuttleRoute.service.ts, src/services/solapi.service.ts
아래 상황들에 대하여 알림톡을 발송하는 기능을 구현했습니다.
- 수요조사 후 노선 미개설 시, 수요조사 한 모든 유저들에게
- 수요조사 후 노선 최종 개설 시, 수요조사 하고 예약하지 않은 모든 유저들에게
=> feat: 노선 개설 관련 알림톡 발송 기능

src/app/events/[eventId]/sales/components/SalesRow.tsx, src/app/events/[eventId]/sales/components/SalesTable.tsx
기존의 문제점
- 스크롤이 왼쪽으로 더이상 도달하지 못함 (왼쪽에 짤린 글자 존재)
- y scroll 이 생겨서 칸이 더 부족해보임
해결
- 스크롤 시작지점이 글자의 시작지점으로 표기되게 변경
- y scroll 가리기
https://github.com/user-attachments/assets/58964621-234a-4800-bd65-3fdfd34aa59e
=> design: 매출 대시보드에 노선명 필드에 y scroll 가리기 및 텍스트 짤리는 이슈해결

src/app/locations/components/Roadview.tsx, src/components/input/CoordInput.tsx
장소 추가/수정하기 페이지에서 설정한 핀의 위치에 가장 가까운 위치의 로드뷰 미리보기를 제공합니다. (방향도 정해짐)
핀의 위치를 조정하면 로드뷰도 함께 조정됩니다.
=> feat: 장소 추가/수정하기에 로드뷰 추가
